[package]
name = "advent"
version = "0.1.0"
authors = ["Josh Comer <jcomer@cvent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
itertools = "0.8"
lazy_static = "1.4"